/**
 * Turn the cropped slabs into responsive WebP renditions.
 *
 * `crop_slabs.py` recovers the slab from each catalogue page at full source
 * resolution. This produces the sizes the site actually serves, and writes the
 * intrinsic dimensions back into src/data/slabs.gen.js so every <img> can carry
 * width and height and reserve its own space — on a page that is almost entirely
 * photography, that is the difference between a calm load and the layout jumping
 * as each slab arrives.
 *
 *   <name>-2000.webp   detail view / lightbox
 *   <name>-1200.webp   full-bleed sections
 *   <name>-800.webp    listing grid
 *   <name>-400.webp    mobile grid, srcset floor
 *
 * Run: npm run slabs   (crops first, then this)
 */
import { readdir, mkdir, writeFile, stat } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "public", "slabs");
const OUT = join(ROOT, "public", "img");

const WIDTHS = [
  { w: 2000, q: 82 },
  { w: 1200, q: 80 },
  { w: 800, q: 78 },
  { w: 400, q: 72 },
];

async function main() {
  await mkdir(OUT, { recursive: true });
  const manifest = {};
  let srcBytes = 0;
  let outBytes = 0;
  let count = 0;

  for (const collection of await readdir(SRC)) {
    const dir = join(SRC, collection);
    if (!(await stat(dir)).isDirectory()) continue;

    await mkdir(join(OUT, collection), { recursive: true });

    for (const file of await readdir(dir)) {
      if (!file.endsWith(".webp")) continue;
      const key = `${collection}/${file}`;
      const inPath = join(dir, file);
      srcBytes += (await stat(inPath)).size;

      const base = file.replace(/\.webp$/, "");
      let intrinsic = null;

      for (const { w, q } of WIDTHS) {
        const info = await sharp(inPath)
          .resize({ width: w, withoutEnlargement: true })
          .webp({ quality: q, effort: 5 })
          .toFile(join(OUT, collection, `${base}-${w}.webp`));
        outBytes += info.size;
        if (w === 2000) intrinsic = { width: info.width, height: info.height };
      }

      manifest[key] = { base: `${collection}/${base}`, ...intrinsic };
      count += 1;
      process.stdout.write(".");
    }
  }

  const file = `/**
 * GENERATED by scripts/process-slabs.mjs — do not edit by hand.
 * Run \`npm run slabs\` after changing the crop or adding catalogue pages.
 */
export const SLABS = ${JSON.stringify(manifest, null, 2)}

/** Widths emitted for each slab, for building srcset. */
export const SLAB_WIDTHS = ${JSON.stringify(WIDTHS.map((x) => x.w))}
`;
  await writeFile(join(ROOT, "src", "data", "slabs.gen.js"), file, "utf8");

  const mb = (b) => (b / 1024 / 1024).toFixed(1);
  console.log(`\n\n✓ ${count} slabs → ${count * WIDTHS.length} renditions`);
  console.log(`  source ${mb(srcBytes)} MB → renditions ${mb(outBytes)} MB`);
  console.log("  wrote src/data/slabs.gen.js");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
